# Generated by Django 2.1.5 on 2019-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
