# Generated by Django 2.1.5 on 2019-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0002_sensors_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='fanStatus',
            field=models.TextField(default='Deactivated', max_length=250),
        ),
        migrations.AddField(
            model_name='sensors',
            name='lightStatus',
            field=models.TextField(default='Deactivated', max_length=250),
        ),
    ]
