# Generated by Django 2.1.5 on 2019-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0003_auto_20190407_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='action',
            field=models.TextField(default='None', max_length=250),
        ),
    ]
