# Generated by Django 2.1.7 on 2019-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0004_sensors_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='humidity',
            field=models.FloatField(default=0.0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='moisture',
            field=models.FloatField(default=0.0, max_length=250),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='temperature',
            field=models.FloatField(default=0.0, max_length=250),
        ),
    ]
